name: Pull request
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs: 
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: Show context
        run: Show context github "${{ toJSON(github) }}" 
        